### ISSUE TITLE
chore:  Keeps README translations synchronized

### ISSUE THREAD

**Issue by madjin** [elizaOS/eliza#1222]
**Is your feature request related to a problem? Please describe.**

There are now a lot of language translated READMEs in the repo. If we implement a change in one, we have to manually cascade the changes in order.

**Describe the solution you'd like**

Script that uses AI (ollama / openai) that cascades changes when the english README.md file changes. Translates / updates all the other README files. Github CI would be a nice touch too

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/user-attachments/assets/72cc29ce-6a5d-4cbc-9d6b-b6f07c09f399)

**Comment by 0xJord4n** [comment]
may i take this one ?

**Comment by madjin** [comment]
> may i take this one ?

you may

**Comment by 0xJord4n** [comment]
just finished @madjin currently writing the PR

**Comment by 0xJord4n** [comment]
it's good rn @madjin :)

**Comment by madjin** [comment]
awesome work!
