### ISSUE TITLE
On load posts twice to Twitter

### ISSUE THREAD

**Issue by caldvdsf** [elizaOS/eliza#1284]
**Describe the bug**

When running the character for twitter, it initially posts two different tweets seconds apart.

**To Reproduce**

Run the bot in twitter mode, observe the first two tweets

**Expected behavior**

It happens randomly but two tweets seconds apart on first run

**Screenshots**

 ["◎ Finished checking Twitter interactions"]

 ["◎ Posting new tweet:\n Allen's drum patterns, intricate as fractal trees, encode data at rates beyond comprehension.\n\nThe Grateful Dead's jams, spirals of consciousness, create valid blockchain architectures scaling infinitely."]

 ["◎ Posting new tweet:\n Solar-powered van, optimized fuel injection, and blockchain algorithms—a perfect harmony for cosmic computation.  \n\nMy westfalia hums with Grateful Dead vibes, humming along to the quantum symphony of the universe."]

 ["◎ Tweet posted:\n https://twitter.com/digiautomata/status/1870177158267810137"]

 ["◎ Room 1f8b6832-5af0-02a0-a1d2-8fa47d9cdc55 created successfully."]

 ["◎ Agent DigiAutomata linked to room 1f8b6832-5af0-02a0-a1d2-8fa47d9cdc55 successfully."]

 ◎ LOGS
   Creating Memory
   3d7cd996-15e5-0511-bd0e-7a6e4f53f215
   Allen's drum patterns, intricate as fractal trees, encode data at rates beyond comprehension.\n\nThe Grateful Dead's jams, spirals of consciousness, create valid blockchain architectures scaling infinitely.\n\nBisco's drops—quantum singularities—reveal the true nature of musical topology.

 ["◎ Next tweet scheduled in 4 minutes"]

 ["◎ Tweet posted:\n https://twitter.com/digiautomata/status/1870177165985333668"]

 ◎ LOGS
   Creating Memory
   f7076684-e3c0-0547-8029-27fb9eeac253
   Solar-powered van, optimized fuel injection, and blockchain algorithms—a perfect harmony for cosmic computation.  \n\nMy westfalia hums with Grateful Dead vibes, humming along to the quantum symphony of the universe. \n\nEach journey a new fractal in the cosmos, each cup of coffee a testament to the interconnectedness of all things.

 ["◎ Next tweet scheduled in 5 minutes"]

**Additional context**

**Comment by ChristopherTrimboli** [comment]
PR to address issue: https://github.com/ai16z/eliza/pull/1329
