### ISSUE TITLE
Reduce load on maintainers

### ISSUE THREAD

**Issue by monilpat** [elizaOS/eliza#1318]
**Is your feature request related to a problem? Please describe.**

Maintaining an open-source project involves managing numerous issues and pull requests. Over time, some of these become inactive or outdated, cluttering the repository and making it challenging to identify current and relevant items. Manually tracking and closing such inactive issues and pull requests is time-consuming and prone to oversight.

**Describe the solution you'd like**

Implementing an automated workflow using the `actions/stale` GitHub Action can streamline this process. This action would automatically mark issues and pull requests as stale after a specified period of inactivity and subsequently close them if no further activity occurs. This automation ensures that the repository remains organized, with outdated or inactive items systematically managed.

**Describe alternatives you've considered**

- **Manual Management**: Regularly reviewing and closing inactive issues and pull requests by hand. However, this approach is labor-intensive and may lead to inconsistencies or delays in addressing stale items.

- **Custom Scripts**: Developing bespoke scripts to handle stale issues and pull requests. While feasible, this requires additional maintenance and may not be as robust or feature-rich as existing solutions like `actions/stale`.

**Additional context**

The `actions/stale` GitHub Action is a widely used tool for managing inactive issues and pull requests. It allows for customization of inactivity periods, messages, and labels, providing flexibility to adapt to the project's specific needs. Implementing this action can improve project maintenance efficiency and enhance contributor engagement by clearly indicating which items require attention.

For more information and configuration options, refer to the official `actions/stale` documentation:

**Comment by shakkernerd** [comment]
Implemented in #1317
