### ISSUE TITLE
v0.1.6 When running on the gitpod , not able to chat in terminal when pnpm start , "Error starting agent for character Eliza"

### ISSUE THREAD

**Issue by onlyzerosonce** [elizaOS/eliza#1328]
**Describe the bug**

When running the Eliza in the gitpod from the readme , it installs successfully. but when I start the eliza with pnpm start it just gets stuck and nothing happens even after waiting for some time.

**To Reproduce**

just deploy it using gitpod link. 
once successfully installed. 
run 
"pnpm start"

**Expected behavior**

Expected behavior is that you should be able to chat with in terminal but it gets stuck and 
**Screenshots**

![image](https://github.com/user-attachments/assets/b67ae146-9d10-4039-8ca2-b79e190332d4)

**Comment by onlyzerosonce** [comment]
⛔ ERRORS
   Error starting agent for character Eliza: 
   {} 

 ["⛔ Error: Invalid cache store: undefined or required configuration missing."] 

 ⛔ ERRORS
   Error starting agents: 
   {}

**Comment by oxSaturn** [comment]
Add `CACHE_STORE=database` to your '.env` file. You might have an old `.env` file. See https://github.com/ai16z/eliza/pull/1308

**Comment by onlyzerosonce** [comment]
this did help start the agent, but then still I am not able to chat in the terminal. 

![image](https://github.com/user-attachments/assets/80f94715-be7b-4145-8d8e-74803c7c61c3)

**Comment by oxSaturn** [comment]
Nah, I don't think chatting in the terminal is supported at the moment. Maybe someone can confirm it.

**Comment by onlyzerosonce** [comment]
I was able to chat with previous version in terminal. 
![WhatsApp Image 2024-12-16 at 13 42 53](https://github.com/user-attachments/assets/379d8d03-481f-4b33-9968-ba4607c45aa7)

**Comment by onlyzerosonce** [comment]
in v0.1.7 this issue got fixed , eliza agent started with default settings.

**Comment by qafariamirhossein** [comment]
Same issue, in v0.1.7:

```
 ⛔ ERRORS
   Error starting agent for character AlphaX: 
   {"length":90,"name":"error","severity":"ERROR","code":"XX000","file":"heapam.c","line":"4194","routine":"simple_heap_update"} 

 ["⛔ error: tuple concurrently updated"] 

 ⛔ ERRORS
   Error starting agents: 
   {"length":90,"name":"error","severity":"ERROR","code":"XX000","file":"heapam.c","line":"4194","routine":"simple_heap_update"}```
