### ISSUE TITLE
connect ETIMEDOUT 104.244.46.63:443

### ISSUE THREAD

**Issue by cxp-13** [elizaOS/eliza#1332]
**Describe the bug**

```
 ⛔ ERRORS
   ERROR:
   {"message":"request to https://api.openai.com/v1/chat/completions failed, reason: connect ETIMEDOUT 104.244.46.63:443","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"}
```

**To Reproduce**

Input some sentences normally, start the trump character and use OpenAI as model provider.

**Expected behavior**
The API can been successfully called on Apipost tools
![image](https://github.com/user-attachments/assets/6520b8d6-472f-449a-85ea-89f1773e35d6)

**Screenshots**

**Additional context**

**Comment by samarth30** [comment]
@cxp-13 seems like your API quota limit for Open ai api has been exceeded.

try recharging this to make it work https://platform.openai.com/
