### ISSUE TITLE
Multiple generateNewTweetLoop method invocations caused multiple tweets to be posted.

### ISSUE THREAD

**Issue by jasonqindev** [elizaOS/eliza#1395]
**Describe the bug**
At [`Yotta Labs`](https://www.yottalabs.ai/), we are transforming global computing into a high-performance, decentralized AI platform. As part of this mission, I integrated the AI Agent functionality and selected the Eliza framework for managing agent-related tasks. 

While configuring the Twitter client and successfully logging into my account, I noticed an issue in the runtime logs: the message `["◎ Next tweet scheduled in 128 minutes"]` appeared twice. This indicates that `generateNewTweetLoop` was called twice, resulting in two independent tweet scheduling loops being initialized.

The issue occurs because the `start` method in `/packages/client-twitter/src/post.ts` calls `generateNewTweetLoop` twice—once at line 174 and again at line 190—without any conditional checks to prevent multiple timers.

**To Reproduce**
1. Add the following code to the relevant `character.json` file:

   ```
   "clients": ["twitter"]
   ```

2. Configure the Twitter-related parameters in the `.env` file, and set `POST_IMMEDIATELY=true` to enable immediate tweet posting.

3. Start the model service.

4. Check Twitter, and you will find that two tweets are posted simultaneously. Additionally, the logs show the message `Next tweet scheduled in xxx minutes` printed twice.

**Expected behavior**
The generateNewTweetLoop method should only be invoked once during the start method, ensuring that only a single tweet scheduling loop is active. This would prevent duplicate logs and redundant scheduling timers.

**Screenshots**
<img width="833" alt="image" src="https://github.com/user-attachments/assets/0ebe87aa-ff46-488d-9961-90daf43b5aab" />

**Additional context**
- File: /packages/client-twitter/src/post.ts
- Method: start
- Lines: 174 and 190
- Observed Behavior: generateNewTweetLoop is called twice without a conditional check, causing two scheduling loops to be initialized.
- Move second generateNewTweetLoop() inside the if (enableActionProcessing)

**Comment by shakkernerd** [comment]
Fixed in #1472
