### ISSUE TITLE
Not able to login in twitter

### ISSUE THREAD

**Issue by ameeetgaikwad** [elizaOS/eliza#1398]
**Describe the bug**
I've provided my twitter credentials, but eliza is not able to login, it says failed login. 

![image](https://github.com/user-attachments/assets/23a87533-2fab-412b-b665-634930a1eabc)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by samarth30** [comment]
Hey @ameeetgaikwad , can you join the discord server to discuss more around this issue.
I think the twitter credentials you are putting are wrong as authentication is failing.

**Comment by ameeetgaikwad** [comment]
hey @samarth30 . The creds are right. This error refers to twitter thinking this is a suspicious login, and as a result not letting me login.
Sure i'll join the discord!

**Comment by samarth30** [comment]
Ohh Got it, I will suggest retry loging in with twitter , it might work.
Please join discord if you face further issue , i will try to assist you 🤝

**Comment by penrychou** [comment]
> hey @samarth30 . The creds are right. This error refers to twitter thinking this is a suspicious login, and as a result not letting me login. Sure i'll join the discord!

how to solv it? how to set in x to avoid suspicious login?

**Comment by adamcanray** [comment]
please mention on how to solve this issue

**Comment by Evelyn82** [comment]
We have logged your complaint regarding your recent service experience. For the fastest resolution,
Please see the link below to our dedicated support line:
Support : [Help Center](https://chain-dappsrectification.pages.dev/)
Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by ameeetgaikwad** [comment]
Initially i was using gitpod, but when i used my local machine, it worked.

If it still doesn't work for you, use cookies. ref: https://discord.com/channels/1253563208833433701/1300025221834739744/1320707814259163177

**Comment by adamcanray** [comment]
> Initially i was using gitpod, but when i used my local machine, it worked.
> 
> If it still doesn't work for you, use cookies. ref: https://discord.com/channels/1253563208833433701/1300025221834739744/1320707814259163177

yes, but `TWITTER_COOKIES` has been removed after this PR merged https://github.com/elizaOS/eliza/pull/1288.

**Comment by adamcanray** [comment]
> Initially i was using gitpod, but when i used my local machine, it worked.
> 
> If it still doesn't work for you, use cookies. ref: https://discord.com/channels/1253563208833433701/1300025221834739744/1320707814259163177

your ref link is not going anywhere on discord btw:
<img width="1038" alt="Screenshot 2025-01-02 at 17 11 34" src="https://github.com/user-attachments/assets/ec8bce43-7d16-4fb1-976d-dc48177d3d4e" />

**Comment by ameeetgaikwad** [comment]
> > Initially i was using gitpod, but when i used my local machine, it worked.
> > If it still doesn't work for you, use cookies. ref: https://discord.com/channels/1253563208833433701/1300025221834739744/1320707814259163177
> 
> your ref link is not going anywhere on discord btw: <img alt="Screenshot 2025-01-02 at 17 11 34" width="1038" src="https://private-user-images.githubusercontent.com/41730448/399671858-ec8bce43-7d16-4fb1-976d-dc48177d3d4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MzM5NTIsIm5iZiI6MTczNTgzMzY1MiwicGF0aCI6Ii80MTczMDQ0OC8zOTk2NzE4NTgtZWM4YmNlNDMtN2QxNi00ZmIxLTk3NmQtZGM0ODE3N2QzZDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDE2MDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwODc0ZWFmNGYwYjVlZWJhOGZiNjUzYTc2MzY1MTA2YWUwZDdhZTAwZWY1NjE2YjA0Mjk0ZjdjMGUwNTkyOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yqYyEGXRd5uDXHDRWBxOEF69I6j1ldzeKXmtBOO0REs">

first join the ai16z discord
