### ISSUE TITLE
Quick start guide bug - pnpm start

### ISSUE THREAD

**Issue by freddymercury** [elizaOS/eliza#1552]
**Describe the bug**
when going through the quickstart guide

Getting an error when using local client (`pnpm start:client`) and init any chat such as `hello`...the output on the service is:

```
-0009-a2c3-83780c350ff3 successfully."] 

 ["◎ Agent tate linked to room 6ac3f59a-67bb-0009-a2c3-83780c350ff3 successfully."] 

 ◎ LOGS
   Creating Memory 
   0c8b6c1c-00b2-0768-8309-564c7d224967 
   hi 

 ["◎ Generating message response.."] 

 ["◎ Generating text..."] 

 ℹ INFORMATIONS
   Generating text with options: 
   {"modelProvider":"gaianet","model":"large"} 

 ℹ INFORMATIONS
   Selected model: 
   qwen72b 

 ◎ LOGS
   Creating Memory 
   2f8f543d-8105-094e-89e8-5ecda88f310f 
   What's the purpose of this conversation? 


file:///Users/dev/rsrc/eliza/packages/adapter-sqlite/dist/index.js:308
        const memories = this.db.prepare(sql).all(...queryParams);
                                              ^
SqliteError: Vector dimension mistmatch. First vector has 768 dimensions, while the second has 384 dimensions.
    at SqliteDatabaseAdapter.searchMemoriesByEmbedding (file:///Users/dev/rsrc/eliza/packages/adapter-sqlite/dist/index.js:308:47)
    at SqliteDatabaseAdapter.createMemory (file:///Users/dev/rsrc/eliza/packages/adapter-sqlite/dist/index.js:240:48)
    at MemoryManager.createMemory (file:///Users/dev/rsrc/eliza/packages/core/dist/index.js:3176:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///Users/dev/rsrc/eliza/packages/client-direct/dist/index.js:275:13 {
  code: 'SQLITE_ERROR'
}

Node.js v23.3.0
/Users/dev/rsrc/eliza/agent:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @elizaos/agent@0.1.7-alpha.2 start: `node --loader ts-node/esm src/index.ts "--isRoot" "--character=characters/tate.character.json"`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

**To Reproduce**
- `pnpm start --character="characters/tate.character.json"`
-  `pnpm start:client`
-  initiate a chat after selecting agent - such as 'hello'
- no response on UI; the service has the error above with the service process exiting code 1

**Expected behavior**

**Screenshots**

**Additional context**

starts up just fine, creates memories etc to the vector db.

using node version 23.3, tried 24.3 - same result
on a mac os - Monterrey - 12.7.6 (intel chip)

using elizaOS version - `v0.1.7-alpha.2`
using `gaianet` as the model provider

**Comment by CryptoUncleSam** [comment]
exactly the same error

**Comment by freddymercury** [comment]
i am closing this as I do not think this is critical. I was able to move past this by using openAI. I was using `gaianet` so I am guessing there is gaianet account problem on my end.

**Comment by freddymercury** [comment]
> exactly the same error

what is your llm provider? gaianet? openai?

**Comment by www222fff** [comment]
same issue with me for gaianet provider, is there fix release or warkaround?

**Comment by harishkotra** [comment]
@www222fff @freddymercury @CryptoUncleSam Harish here from the Gaia team. 

We're actively looking into this and will push a PR with a fix soon!

**Comment by issa-me-sush** [comment]
seems to be fine with the latest - v0.1.7

**Comment by harishkotra** [comment]
@www222fff @freddymercury @CryptoUncleSam try the latest v.0.1.7 and it works without this issue. Thanks @issa-me-sush for the update.

**Comment by twopats** [comment]
having this issue as well! my package.json doesn't seem to have start:client
