### ISSUE TITLE
I have a twitter premium subscription and MAX_TWEET_LENGTH  to 2500 but I can't to post a tweet with more than 280 characteres

### ISSUE THREAD

**Issue by 0x3N3jVhPUV** [elizaOS/eliza#883]
**Describe the bug**
I have a Premium twitter subscription, I'm using the latest coockies, in eliza/packages/client-twitter/src/post.ts, I changed MAX_TWEET_LENGTH  to 2500;  but my agent cannot post more than 280 characters on X. 
Here is what I'm getting when I'm trying to post with more thant 280 characters:
"Error sending tweet; Bad response: {
  errors: [
    {
      message: 'Authorization: Tweet needs to be a bit shorter. (186)'
...."
 
**To Reproduce**
1- Get a premium twitter subscription
2- Make sure you ar using the latest coockies
3- Change MAX_TWEET_LENGTH  to 2500
4- Run the agent

**Expected behavior**

 Since I have a twitter premium subscription ,I should be able to post a tweet with more than 280 characteres.

**Screenshots**
![image](https://github.com/user-attachments/assets/fbfdf249-6bce-42da-9b59-1655190e2295)

Question:
What should I do in order to post more than 280 characters on X?

Regards

**Comment by CodingTux** [comment]
Wait for few hours if you purchased the premium recently. Also try with different length size first like 500, 1000, 1500 etc and check when it starts failing. Another thing you can do is check the generated response length.

**Comment by oxSaturn** [comment]
Seems to be a bug fixed in agent-twitter-client https://github.com/ai16z/agent-twitter-client/pull/18

**Comment by 0x3N3jVhPUV** [comment]
Hello, @CodingTux and @oxSaturn,
 
I fixed it. You can check it here: https://github.com/ai16z/agent-twitter-client/pull/19/commits/552eecbacd352295f59337054a1c0d0d0dfb7e51

Thank you for your answers

**Comment by 0x3N3jVhPUV** [comment]
> Seems to be a bug fixed in agent-twitter-client [ai16z/agent-twitter-client#18](https://github.com/ai16z/agent-twitter-client/pull/18)

Indded but when I tried to use the function sendNoteTweet(), I have the following error:
 ERRORS
   Error sending tweet: 
   {} 
   
After buildind, I checked  eliza/node_modules/agent-twitter-client/src/scraper.ts and the function  sendNoteTweet() is not in the file.

**Comment by oxSaturn** [comment]
> > Seems to be a bug fixed in agent-twitter-client [ai16z/agent-twitter-client#18](https://github.com/ai16z/agent-twitter-client/pull/18)
> 
> Indded but when I tried to use the function sendNoteTweet(), I have the following error: ERRORS Error sending tweet: {}
> 
> After buildind, I checked eliza/node_modules/agent-twitter-client/src/scraper.ts and the function sendNoteTweet() is not in the file.

The code was merged without a new release. cc @lalalune Can you please cut a release for `agent-twitter-client`?

**Comment by shakkernerd** [comment]
Implemented in #1339
